### ISSUE TITLE
Avatar upload in tl_member funktioniert nicht

### ISSUE THREAD

**Issue by markocupic** [Kuestenschmiede/ForumBundle#1]
Vielen Dank für die neue Version des Forums. Installation und upgrade vom alten Forum hat rribungslos geklappt.
Einen kl. Bug habe ich noch entdeckt. 
Der Avatar upload in tl_member funktioniert bei mir noch nicht.
LG Marko

**Comment by coastforge-mei** [comment]
Moin Marko,
den Fehler kann ich in der aktuellen Version nachstellen. Wir schauen uns das an.
Danke Matthias

**Comment by markocupic** [comment]
Hallo Matthias
Wenn du möchtest, kann ich das heute Abend auch debuggen. 
Kannst mir Bescheid geben, wenn du viel um die Ohren hast.
Lg Marko

**Comment by coastforge-mei** [comment]
Hi Marko,
hab' gerade mal kurz in zwei Umgebungen getestet. In der einen funktioniert es. In der anderen nicht. Hab' noch keine Idee warum. Du kannst das gerne mal debuggen. Ansonsten gehen wir da in der nächsten Woche noch mal ran.
Danke Matthias

**Comment by markocupic** [comment]
Ich habe den Fehler gefunden und Änderungen in 2 Dateien gemacht. Hier mein Vorschlag:
vendor\con4gis\forum\Resources\contao\dca\tl_member.php
```php
    
    /**
     * @param $dc
     * @return string
     */
    public function setUploadFolder($varValue, $dc)
    {

        $uploadFolder = "files/userimages";
        $iMemberId = $dc->id;

        if ($iMemberId > 0)
        {
            $uploadFolder = $uploadFolder . '/user_' . $iMemberId;
        }

        $GLOBALS['TL_DCA']['tl_member']['fields']['memberImage']['eval']['uploadFolder'] = $uploadFolder;
    }
    
```
und in
C:\xampp\htdocs\jade\vendor\con4gis\forum\Resources\contao\widgets\Avatar.php

```php

    

    /**
     * Trim values
     * @param mixed
     * @return mixed
     */
    public function validator($varInput)
    {
        $rootDir = System::getContainer()->getParameter('kernel.project_dir');

        $strUploadTo = 'system/tmp';

        // No file specified
        if (!isset($_FILES[$this->strName]['name'][0]))
        {
            return;
        }

        // Specify the target folder in the DCA (eval)
        if (isset($this->arrConfiguration['uploadFolder']))
        {
            $strUploadTo = $this->arrConfiguration['uploadFolder'];

            // Add user-based subfolder to target folder to prevent overwriting files with duplicate names.
            if (TL_MODE === 'FE')
            {
                $this->import('frontenduser');
                $strUploadTo = 'files/userimages/user_' . $this->frontenduser->id;
            }
            else
            {
                if (!$strUploadTo)
                {
                    return;
                }
            }

            // Create the folder if it does not exist.
            if (!is_dir($rootDir . '/' . $strUploadTo))
            {
                new Folder($strUploadTo);
            }
        }

        return $this->objUploader->uploadTo($strUploadTo);
    }


```
$strUploadTo sollte ohne TL_ROOT an FileUpload::uploadTo() übergeben werden.

**Comment by coastforge-mei** [comment]
Hallo Marko,
hab' Deine Änderung in den Trunk "gemerged" und schließe hiermit dieses Issue.
Dankbare Grüße
Matthias
