### ISSUE TITLE
Bilder speichern falsch

### ISSUE THREAD

**Issue by Sizoberz** [Kuestenschmiede/ForumBundle#10]
Meine Installation von contao ist im /web Verzeichnis. Die Bilder werden eine Ebene tiefer im Root-Verzeichnis in einem Datumsordner gespeichert, obwohl ich im Modul ein Ordner im files-Verzeichnis angegeben habe. So werden die Bilder nicht gefunden.

**Comment by coastforge-mei** [comment]
Wir werden das überprüfen. Die Auswahl findet ja im Modul statt und sollte bspw. ein solches Ergebnis darstellen "files/forum/images". Ggf. ist der Ordner in der Dateiverwaltung geschützt.

**Comment by coastforge-rro** [comment]
In der nächsten Version sollte es wieder korrekt funktionieren.

**Comment by Sizoberz** [comment]
👍 Danke!
