### ISSUE TITLE
Kartenlink im Beitrag

### ISSUE THREAD

**Issue by Sizoberz** [Kuestenschmiede/ForumBundle#11]
Die Kartenlinks auf den Forenbereichsseiten funktionieren, die Links im Beitrag bringen einen Fehler
Error: Internal Server Error

**Comment by coastforge-cro** [comment]
In der aktuellen Version 3.6.0 tritt der Fehler nicht mehr auf, beide Kartenlinks leiten auf die Karte weiter. Ich werde das Issue nun schließen.
