### ISSUE TITLE
Persönliche Nachricht

### ISSUE THREAD

**Issue by Sizoberz** [Kuestenschmiede/ForumBundle#12]
Aktiviert man die Option  Persönliche Nachrichten
"Button für Persönliche Nachrichten im Profil anzeigen"
wird dieser unter angezeigt - der Link führt allerdings zur Hompeage, da er so aussieht
https://www.domain.de/#
und öffnet nicht das Nachrichten Fenster wie erwartet, welches man über das Modul einbauen kann

**Comment by thepixture** [comment]
Den Fehler hab ich im Firefox auch.
> ReferenceError: event is not defined[Weitere Informationen] jquery-1.12.4.min.js line 2 > eval:176:7
_sendMessageTo
https://code.jquery.com/jquery-1.12.4.min.js line 2 > eval:176:7
onclick

Im Chrome wird das Modal-Fenster für die Nachricht angezeigt.

**Comment by Sizoberz** [comment]
Oh ja - im Chrome, Internet Explorer und Edge funktioniert es bei mir. Sehr schade das Firefox nicht funktioniert, aber vielen Dank @thepixture!

**Comment by coastforge-rro** [comment]
Wir werden versuchen, das Problem im Firefox zu beheben.

**Comment by Sizoberz** [comment]
👍

**Comment by coastforge-rro** [comment]
In der nächsten Version tritt der Fehler im Firefox nicht mehr auf.
