### ISSUE TITLE
Bewertung

### ISSUE THREAD

**Issue by Sizoberz** [Kuestenschmiede/ForumBundle#13]
Habe die Bewertung aktiviert - sehe aber nirgens eine Möglichkeit Beiträge über o.ä. Sterne zu bewerten

**Comment by thepixture** [comment]
Schau mal, ob Du "Berechtigungen festlegen" in der Forumsstruktur aktiviert hast.

**Comment by Sizoberz** [comment]
Habe ich, sehe aber keine spezielle Berechtigung für Forenmitglieder, die eine Bewertung regelt

**Comment by thepixture** [comment]
Stimmt, ich dachte da gabs eine Einstellung. Bekommst Du einen Fehler in der Console? Bei mir funktioniert die Bewertung.

**Comment by Sizoberz** [comment]
Nein wie gesagt geht der Link einfach auf die Startseite

**Comment by Sizoberz** [comment]
Nein. Wo genau meinst Du im Manager beim update?

**Comment by thepixture** [comment]
Ich meine die Entwickler-Konsole im Browser

**Comment by Sizoberz** [comment]
Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/

Das kommt wenn ich einen Beitrag öffne

**Comment by coastforge-rro** [comment]
Die Möglichkeit zur Bewertung sollte zur Verfügung stehen, wenn man einen Beitrag verfasst.

**Comment by Sizoberz** [comment]
Wenn man einen neuen Beitrag verfasst? Denke man kann Beiträge bewerten?
Aber auch da sehe ich nichts. Bei einem neuen Beitrag sieht es so aus:
![image](https://user-images.githubusercontent.com/34723382/44018905-89799f38-9edd-11e8-9fcb-28959467e13e.png)

Ein vorhandener, den ich gerne bewerten würde sieht so aus:
![image](https://user-images.githubusercontent.com/34723382/44018942-ab636598-9edd-11e8-8d76-dc61e0f56e5f.png)

Das Forum sieht so aus:
![image](https://user-images.githubusercontent.com/34723382/44019000-d8402344-9edd-11e8-939f-d5ae7a0de6fd.png)

Wo sollte die Kommentarfunktion erscheinen?

**Comment by coastforge-rro** [comment]
Wichtig ist die Unterscheidung zwischen Thema und Beitrag. In dem 1. Screenshot wird ein neues Thema erstellt. Da kann man noch nichts bewerten, da die Themen bewertet werden. Um das eben erstellte Thema zu bewerten, muss man einen neuen Beitrag zu dem Thema erstellen, also antworten.

**Comment by Sizoberz** [comment]
Ah ok - sorry, wenn man´s weiß ist´s logisch. Hatte nur eine andere Erwartungshaltung der Funktion.
Vielen Dank @coastforge-rro und @thepixture

**Comment by coastforge-rro** [comment]
Kein Problem.
