### ISSUE TITLE
Fehler beim Ansehen eines Themas

### ISSUE THREAD

**Issue by seibtph** [Kuestenschmiede/ForumBundle#15]
Wenn ich ein Thema anklicke, erscheint ein Fehler. Es steht allerdings nur Error da, ohne eine hilfreiche Fehlermeldung. Das Anlegen des Themas ging noch und sonst scheint der Rest auch zu funktionieren.

Ich nutze die aktuelleste Foren-Version 3.2.5.
Contao-Version: 4.6.6

![forum_error](https://user-images.githubusercontent.com/17127525/47423741-11dbb100-d786-11e8-9ced-e1febd1c6aae.png)

**Comment by coastforge-cro** [comment]
Hallo, 
wir haben das Problem untersucht und haben festgestellt, dass es mit der Contao 4.5.er zusammenhängt, da ab der 4.5 die Symfony Security verwendet wird. Das Forum ist an der Stelle noch nicht auf den neuen Mechanismus umgebaut. Wir arbeiten an einer Lösung.

**Comment by MicioMax** [comment]
This is because of missing tl_session table.
Copying from an older contao database "solves" the problem... of course this is just a workaround.

**Comment by coastforge-cro** [comment]
> This is because of missing tl_session table.
> Copying from an older contao database "solves" the problem... of course this is just a workaround.

Thanks for the reply and your workaround. Keep in mind that the logic that uses the tl_session table (e.g. the recognition of online users) could produce incorrect results, since I don't think Contao 4.6 still updates the table. But this may be a appicable workaround until these parts of the forum are rewritten to be compatible with Contao 4.6.

**Comment by MicioMax** [comment]
Yes, I'm aware of that. I think it should be done reading the session cookie, but I've no time right now to look at it.

**Comment by coastforge-rro** [comment]
This bug should be fixed in the next version.

Dieser Bug sollte in der nächsten Version behoben sein.

**Comment by MicioMax** [comment]
I can confirm...  it works also without the tl_session table.
Thank you!

**Comment by coastforge-rro** [comment]
> I can confirm... it works also without the tl_session table.
> Thank you!

Thank you for the confirmation.
