### ISSUE TITLE
FE_USER_LOGGED_IN and BE_USER_LOGGED_IN wrong usage

### ISSUE THREAD

**Issue by MicioMax** [Kuestenschmiede/ForumBundle#17]
I got some errors/warnings running forum, and looking at them I found the 2 constants, which should be defined only if inside corresponding modules.
In fact, in php7.2 they give a warning if not defined, and evaluate as the corresponding string:

`FE_USER_LOGGED_IN == 'FE_USER_LOGGED_IN'`
and
`'BE_USER_LOGGED_IN == 'BE_USER_LOGGED_IN'`

which, if evaluated as boolean, are taken as TRUE value even if not defined.
BTW, I've seen that those constants are NOT defined when calling functions by ajax, so correcting the problem like this : 

```
	private static function feUserLoggedIn() {
		if(defined('FE_USER_LOGGED_IN'))
			return FE_USER_LOGGED_IN;
		return false;
	}
```
Is not a solution, because of ajax calls.
Replacing with this works :
```
	private static function feUserLoggedIn() {
		if(defined('FE_USER_LOGGED_IN'))
			return FE_USER_LOGGED_IN;
		return true;
	}
```
but then I don't see the point of checking for those constants, as result will be always true.

**Comment by coastforge-rro** [comment]
These constants are remnants of earlier Contao versions. They will be replaced in the next version. Please note the master branch contains the replacement, but has a dependency on the CoreBundle master branch.
