### ISSUE TITLE
Contao 4.6 - Exception\ServiceNotFoundException when using logger

### ISSUE THREAD

**Issue by MicioMax** [Kuestenschmiede/ForumBundle#18]
On Contao 4.6 symphony4 made all services private (also logger, which is overkilling, imho).
You get this exception when try to log from code : 

`Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "The "logger" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead."`

The "simplest" solution I found is to create a public alias to logger service, which (afaik...) means to create a dependency extension class, a services.yml file and so on.
I tried to use dependency injection of this service in classes that uses it, but no way... my skills on symphony are too limited.
If you're interested on my "simple" solution I can drop a pull request.

**Comment by coastforge-rro** [comment]
I have removed the line that attempts to use the logger until we have found a proper solution. I would appreciate any input you can give.

**Comment by MicioMax** [comment]
I have a "solution" in my tree, but I think is a bit overkilling.
I had to add a DependencyInjection extension, which in order loads a yaml file with a service alias (aliasing 'logger' service to 'con4gis.logger' one, which is made public).
The public service can then be used in the old way, getting it from container.
Not sure that this is the best solution... all "dependency injection" stuff seems to me a useless mess that complicates all simple code.
I've seen that other packages simply call \System\log(), but I found it too late and didn't try it.
I'm a newbie on Symfony, so all I can do is trial and error!

**Comment by coastforge-cro** [comment]
The proper way to deal with this would be to refactor the forum code to be able to inject the logger via the Dependency Injection Container. Introducing a additional service to just alias another service is, as you said, a bit overkilling. I will close this issue now.
