### ISSUE TITLE
Anzeige des richtigen Namens im Beitrag funktioniert nicht

### ISSUE THREAD

**Issue by thepixture** [Kuestenschmiede/ForumBundle#19]
Wenn man die Einstellung "Verwende richtige Namen anstelle des Benutzernamens" auf Vor- und Nachnamen anzeigen einstellt, wird innerhalb des Beitrags trotzdem der Benutzername angezeigt. In der Übersicht der Beiträge wird es korrekt ausgegeben.

**Comment by coastforge-rro** [comment]
In der nächsten Version wird dies korrigiert.
