### ISSUE TITLE
No e-mail notification from forum

### ISSUE THREAD

**Issue by MicioMax** [Kuestenschmiede/ForumBundle#20]
I'm trying the notifications (both for post changes and private messages), with following results:

- using FILE gateway, the messages is sent and I can find the resulting file
- using EMAIL gateway, no message is sent

Digging a bit into e-mail code, I've seen that the recipients field is empty ($objDraft->getRecipientEmails(), on terminal42/notification_center/library/NotificationCenter/Gateway/Email.php, around line 140).
I still don't know if it's a problem of forum or notification center.

**Comment by coastforge-rro** [comment]
You need to provide the recipient(s) in the backend settings for each notification.You can use the token ##user_email##, which the forum will replace with the users' email address. If for whatever reason the address (or any other token) is an empty string, an exception will be thrown and the NotificationCenter code is never called.

**Comment by MicioMax** [comment]
Ahhh! I didn't get it!
A bit complicated to setup but quite flexible...
Thank you, closing.
