### ISSUE TITLE
Suggestion about storing draft HTML in database for messages

### ISSUE THREAD

**Issue by MicioMax** [Kuestenschmiede/ForumBundle#21]
Hi,
I was trying the "code snippet" plugin on forum and it is "erased" when sending the message.
The code strips all "pre" (and probably also "code") fields, and all HTML from posts before storing in database.
I had this problem also on previous forum version (contao_forum) and I solved patching it in many places to have the whole html stored into database, without converting it to text.
I did the same stuff in new code, and it works well.
If you're interested, in my fork there's an "keephtml" branch with the needed patches.
Btw, storing the whole html makes (imho...) the whole BBCODE handling useless, so I removed it.
With the patched code you can use html formatting in all posts.

**Comment by MicioMax** [comment]
You can see al this working on my (still temporary) website www.timberstruct.eu.
I'm finishing the forum fixings before putting it on right domain name.

**Comment by coastforge-rro** [comment]
So basically, this allows users to inject HTML into your website?

**Comment by MicioMax** [comment]
Well, sort of.
Of course the "dangerous" tags are stripped out.
