### ISSUE TITLE
Private messages

### ISSUE THREAD

**Issue by MicioMax** [Kuestenschmiede/ForumBundle#22]
Hi,
I'm examining the notification part of forum, starting by private messages.
First issue : the field "admin_email" is not set in ForumController.php : 

```
                    $notificationArray = unserialize($result['mail_new_pm']);
                    $notificationData['user_name'] = $aRecipient['username'];
                    $notificationData['user_email'] = $aRecipient['email'];
                    $notificationData['responsible_username'] = $this->getUser()->username;
                    $this->container->get('contao.framework')->initialize();

```
so if you set the "reply to" field  in notification you get a "mysterious error" telling that some mandatory field is missing. That's because the ##admin_email## doesn't get substituted and triggers an exception in Email code.
Solution : 

```
                    $notificationArray = unserialize($result['mail_new_pm']);
                    $notificationData['user_name'] = $aRecipient['username'];
                    $notificationData['user_email'] = $aRecipient['email'];
                    $notificationData['responsible_username'] = $this->getUser()->username;
                    $notificationData['admin_email'] = $this->getUser()->email;
                    $this->container->get('contao.framework')->initialize();

```
Another problem : ##link## is an allowed tag in text body (I don't know its purpose for private messages...) but it doesn't get substituted in body, so you get an e-mail with ##link## inside text.
It would be useful to have some ##subject## and ##text## and ##html## tags for private messages.
I'll try to add them.

**Comment by MicioMax** [comment]
Here a commit that add the enhancements above : 
https://github.com/MicioMax/ForumBundle/commit/7e47b99a1354907a2f3d3cc42af92465d43a8b02

**Comment by coastforge-rro** [comment]
Unfortunately I forgot about this part when I revised the notifications recently. [This commit](https://github.com/Kuestenschmiede/ForumBundle/commit/a7892d277b95891959f2e09dd7f8e82dff5d38e9) uses the new system. I have also added the ##message## and ##subject## tokens. 

The link token contains a link to the Contao page containing the PM module (although this needs to be configured in the forum module to work properly).

**Comment by MicioMax** [comment]
Good, I reverted to yours tags, but added admin_email to both text and html : 

https://github.com/MicioMax/ForumBundle/commit/82f0f717458533954a26c9021ca617c2e5d447e0

Btw... I guess you don't like to have the html stored in db, right ? Because I need it, and from here I guess I must keep diverging from your tree. For notifications, I'll need to have a "html_message" tag too, for example, and clean "message" from html codes.

**Comment by coastforge-rro** [comment]
Why do you need the amin email in the text/html? 

There is nothing wrong with storing html in the database. The problem is it is a security issue to render html input from the user.

**Comment by MicioMax** [comment]
The "admin_email" is just a candy to have some text like "you received a pm from somebody (some@body.net)".
About HTML, I'll try to secure it at most (later... before I must finish the patches), but I need it because of code snippets problems, and also because I want html formatting and images inside the forum.
Code snippets are a must for me, as the website I'm working on is about programming of embedded controllers, and you can't solve it without stored html, imho, without some really complicated ways.

**Comment by coastforge-rro** [comment]
The admin email is the email set in the Contao backend. If you want to display the user email along with the user name, an appropriate tag could be added, but I do not think it is a good idea to publish a users email address without their consent, legally, but also because a PM function in a forum specifically allows users to privately communicate with each other without the need to know personal information about each other. 

Closing this issue since I expect this to be our final stance.
