### ISSUE TITLE
Underline format

### ISSUE THREAD

**Issue by toteph42** [Kuestenschmiede/ForumBundle#23]
Using CM 1.1.2, Contao 4.6.10, Forum 3.3 and do not have Button "Underline" in ckeditor (using default buttons). Tried to comment out `config.removeButtons` in config.js. Nothing changed.

**Comment by coastforge-mei** [comment]
Today I add a plugin for basicstyles. With this you can use Underline, Subscript and Superscript Buttons. We will rolle out a new release this afternoon.
