### ISSUE TITLE
Erweiterung der Notification Tags bei Benachrichtigung von neuen Posts

### ISSUE THREAD

**Issue by markocupic** [Kuestenschmiede/ForumBundle#24]
Hallo liebes Küstenschmiede Team
Ich versuche seit Stunden die Notification Tokens zu erweitern. Ich habe dafür eine neues lokales [Bundle ](https://github.com/markocupic/jade_bundles/tree/master/src/markocupic/contao-con4gis-forum)gebaut. Im Backend funktioniert die Zuweisung im Notification Center soweit. 

Im Frontend generiere ich eine Fehlermeldung " The token 'user_*' has not been defined." Um den Tokens die Werte zu übergeben, nutze ich den sendNotificationMessage-Hook des Notification Centers.

Die Fehlermeldung wird [hier ](https://github.com/Kuestenschmiede/CoreBundle/blob/2fdff66d864f38eb9cfafea17b04d6c74f016951/Resources/contao/classes/notification/C4GNotification.php#L52)geworfen. Kommentiere ich die Zeile aus, funktioniert auch alles wunderbar.  Es scheint, als ob der Hook zu spät kommt und die Tokens zu früh auf Inhalt geprüft werden. 

Zu finden ist die Erweiterung hier:
https://github.com/markocupic/jade_bundles/tree/master/src/markocupic/contao-con4gis-forum

Wie gelingt es mir dies updatesicher zu programmieren?

Freue mich auf einen Hint ;-)

Besten Dank!

**Comment by markocupic** [comment]
Update:
Erwähnte Fehlermeldung in [C4GForumSubscription ](https://github.com/Kuestenschmiede/ForumBundle/blob/accfdbcf67449510013514d01ea56691e27e8a69/Resources/contao/classes/C4GForumSubscription.php#L391)tritt nicht auf, wenn ich in der config.php die NC-Settings nur fürs Backend zulasse.  
```php
if(TL_MODE === 'BE')
{
    // Notification Center-Einstellungen 
}
```
[Siehe ](https://github.com/markocupic/jade_bundles/blob/004839a23363fa0d8902831b6130a3182049f8f8/src/markocupic/contao-con4gis-forum/src/Resources/contao/config/config.php#L14)

Komischerweise werden die Notifications bei neuen Posts dann trotzdem gesendet.

**Comment by coastforge-rro** [comment]
Sorry für die späte Rückmeldung.

Wir haben das Versenden der Notifications inklusive der Zuweisung der Token gekapselt, um sicherzustellen, dass immer alle Token gesetzt sind. Der Hook des Notification Centers greift an der Stelle nicht (und kann das auch nicht, unabhängig von der Reihenfolge). Die Werte werden in C4GForumSubscription ab Zeile 379 gesetzt. Da müsste man ansetzen. Wir ziehen die Möglichkeit in Betracht, eigene Hooks in con4gis einzubauen, damit könnten wir an der Stelle weitere Token befüllen. Leider fehlt uns dafür momentan die Zeit.

Im Moment gibt es also keine Möglichkeit, das updatesicher aufzubauen.

**Comment by markocupic** [comment]
Hallo @coastforge-rro 

Besten Dank für die Rückmeldung. 
Ich konnte das [hier](https://github.com/markocupic/jade_bundles/tree/master/src/markocupic/contao-con4gis-forum) updatesicher aufbauen. 
Unschön ist, dass [hier](https://github.com/Kuestenschmiede/CoreBundle/blob/2fdff66d864f38eb9cfafea17b04d6c74f016951/Resources/contao/classes/notification/C4GNotification.php#L51) geprüft wird, ob die Tokens befüllt sind oder nicht. Zu diesem Zeitpunkt haben meine Custom-Tokens noch keinen Wert zugewiesen. Eben deshalb wird dann eine Fehlermeldung geworfen. Meine Zuweisung kommt dann erst über den [sendNotificationMessage-Hook](https://github.com/markocupic/jade_bundles/blob/61f09339806a0d98d0f22230218feab8d78d881f/src/markocupic/contao-con4gis-forum/src/Resources/contao/hooks/SendNotificationMessage.php#L43). Ich frage mich, wieso die Prüfung [an der Stelle](https://github.com/Kuestenschmiede/CoreBundle/blob/2fdff66d864f38eb9cfafea17b04d6c74f016951/Resources/contao/classes/notification/C4GNotification.php#L51) nötig ist. Wäre sie nicht, würde es sehr gut funktionieren. Evtl. könnte man die Prüfung auf nur einige wenige Tokens beschränken. 

Nun gut... Gelöst habe ich das Problem, indem in der [config.php](https://github.com/markocupic/jade_bundles/blob/61f09339806a0d98d0f22230218feab8d78d881f/src/markocupic/contao-con4gis-forum/src/Resources/contao/config/config.php#L14) meiner Extension die Tokens nur im **Backend Mode** gesetzt werden. 
Ist halt nicht gerade state of the art. 

Wäre schön dazu ein Feedback zu kriegen.

Lg Marko

**Comment by coastforge-rro** [comment]
Achso. Jetzt habe ich die Lösung auch verstanden. Da müsste sich was machen lassen. Ich melde mich später (heute) nochmal.

Die Prüfung nehmen wir vor, da wir in der Vergangenheit Probleme mit nicht gefüllten Token hatten. Wir hielten es für besser, die Notification in dem Fall nicht zu verschicken, statt ungefüllte Token als Klartext in der Mail zu haben.

**Comment by coastforge-rro** [comment]
Mit den jüngsten Änderungen ist es möglich, in der Config weitere Token hinzuzufügen, ohne dass Fehler verursacht werden. Es werden lediglich die standardmäßig vorhandenen Token geprüft. 

Die hinzugefügten Token müssen natürlich weiterhin mit einem Hook ins NC gefüllt werden. 

Ein Update ist heute geplant.

**Comment by markocupic** [comment]
Das ist super!
Vielen Dank dafür ;-)
Liebe Grüsse 
Marko
