### ISSUE TITLE
Bug bei Notifications auch unter Version 3.7.1 UND CONTAO 4.7

### ISSUE THREAD

**Issue by markocupic** [Kuestenschmiede/ForumBundle#25]
Hallo liebes Küstenschmiede Team
Auch unter der aktuellen Forum-Version ist es nicht möglich, die Benachrichtigungsfunktion bei neuen Posts zu nutzen. Fehlermeldungen erhalte ich nur, wenn ich [hier](https://github.com/Kuestenschmiede/ForumBundle/blob/2b37a14cae98e37ac7871046dd045a7c8619b7c5/Resources/contao/classes/C4GForumSubscription.php#L391) die Zeile anpasse und mir den Fehler per E-Mail zusende. 
```php
mail('my-email-address@foo.ch', 'Error message', $e->getMessage());
```

Folgende 2 Fehlermeldungen treten dabei auf:
_The primary key has not been set
The registry already contains an instance for tl_c4g_forum_thread_subscription::id(6)_

Patchen kann ich das, indem ich die beiden Model-Methoden in den Klassen
**C4GForumSubscriptionModel**, **C4GThreadSubscriptionModel** 
anpasse/umschreibe:

```php
 /**
     * @param $forumId
     * @param $memberId
     * @return mixed
     */
    public function findByForumAndMember($forumId, $memberId)
    {
        $arrColumns = array(
            self::$strTable . '.pid=?',
            self::$strTable . '.member=?'
        );
        $arrValues = array(
            $forumId,
            $memberId
        );

        return static::findOneBy($arrColumns, $arrValues);
    }
```

und 

```php
/**
     * @param $threadId
     * @param $memberId
     * @return mixed
     */
    public function findByThreadAndMember($threadId, $memberId)
    {
        $arrColumns = array(
            self::$strTable . '.pid=?',
            self::$strTable . '.member=?'
        );
        $arrValues = array(
            $threadId,
            $memberId
        );

        return static::findOneBy($arrColumns, $arrValues);
    }
```

**Comment by coastforge-mei** [comment]
Moin Marko,

erst einmal rechtherzlichen Dank für Deinen Einsatz. In der [3.7.2](https://github.com/Kuestenschmiede/ForumBundle/releases/tag/v3.7.2) sind Deinen beiden Anpassungen jetzt übernommen. Bzgl. der Notifications werden wir am Ball bleiben.

Beste Grüße
Matthias

**Comment by markocupic** [comment]
Hallo Matthias
Wow, das ging aber schnell! Mein Dank geht zurück für deine grosse Arbeit am Forum.
Liebe Grüsse
Marko
