### ISSUE TITLE
Contao 4.9 + Private Message

### ISSUE THREAD

**Issue by toteph42** [Kuestenschmiede/ForumBundle#26]
Hi,
ich habe ein `(forum) Persönliche Nachrichten` eingebunden. Geht aber nicht, da im `manager-bundle/src/Resource/skeleton/config/config.yml` 

`content_type:`
     `       nosniff: true` 

angegeben ist. damit werden auf der Seite keinerlei css oder js Dateien geladen.

**Die Ressource von "https://xxx/bundles/con4giscore/vendor/ckeditor/ckeditor.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).**
**Die Ressource von "https://xxx/bundles/con4giscore/vendor/font-awesome/css/font-awesome.min.css" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).**

**Comment by coastforge-cro** [comment]
Hi, danke für deine Meldung. Wir haben das Problem finden und beheben können. Im nächsten Forum-Release wird der Fehler behoben (kommt vorraussichtlich noch diese Woche).

**Comment by coastforge-mei** [comment]
Der Fehler wurde mit der Version 3.10.4 behoben.
