### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by toteph42** [Kuestenschmiede/ForumBundle#28]
Hi,
Contao 4.9.9, con4gis-Forum 3.11.2

Picture uploading works as expected and a link is automatically generated. But...

1. With `Upload File` button, it is possible to upload a file. A directory named with the actual date, but no link is generated in FE. Since file name is encrypted, user has  no chance to add a valid link...
2. The `Link` button also offers to upload files. Unfortunately directory named with the actual date is created, but no file is stored within. Additionally no link is generated...

Is there any chance to allow user to upload .zip files as specified in con4gis settings and add a valid link in a post?

**Comment by coastforge-rro** [comment]
We noticed the upload from the Link button wasn't working and included a fix in the our CoreBundle. However, everything else was working, inlcuding zip files. Note that these must be enabled in the Contao settings, not the con4gis settings.
