### ISSUE TITLE
Fehler beim Einfügen einer Seite

### ISSUE THREAD

**Issue by arboc** [Kuestenschmiede/ForumBundle#29]
Nachdem ich con4gis forum installiert und eingebunden habe, bekomme ich beim Anlegen einer neuen Seite folgenden Fehler:

```
An exception occurred while executing 'UPDATE tl_module SET c4g_forum_sitemap_updated=0 WHERE type='c4g_forum' AND c4g_forum_sitemap=1 AND c4g_forum_sitemap_filename!=''':
  
SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: ' '
```

Soweit ich das erkennen kann liegt es an `c4g_forum_sitemap=1`.   
Hier fehlen Anführungsstriche: `c4g_forum_sitemap='1'`

**Comment by coastforge-rro** [comment]
Das Problem wurde uns in der Vergangenheit schon gemeldet, aber wir konnten es bisher nicht nachstellen. Wir vermuten, es hängt irgendwie mit anderen Bundles zusammen, die in Kombination mit dem Forum dieses Problem verursachen. Wenn möglich, könntest du deine composer.json posten, dann könnten wir eine identische Umgebung aufsetzen und versuchen, das Problem nachzustellen.

An den Anführungszeichen liegt es nicht.

**Comment by arboc** [comment]
Ich habe jetzt ein "nackte" Contao 4.9 Installation aufgesetzt. Einzige Erweiterung das Forum:  
Der Fehler tritt dennoch auf.

Auch wenn ich die SQL-Abfrage direkt an der DB ausführe, erhalte ich den Fehler. Wenn ich die Anführungsstriche setze, dann nicht.  
Ich nehme an, es liegt an der DB- Version oder -Konfiguration. Wir verwenden 10.3.27-MariaDB-0+deb10u1 - Debian 10.   
Das `c4g_forum_sitemap` ist als char(1) definiert und nicht als tinyint(1). Ich vermute, dass die DB bei der Abfrage ohne Anführungsstriche damit ein Problem hat.

Ich habe die Anführungsstrich jetzt mal im Programmcode eingetragen, und es funktioniert.

**Comment by arboc** [comment]
Hier noch die composer.json:  

```json
{
    "type": "project",
    "require": {
        "con4gis/forum": "^4.0",
        "contao/conflicts": "*@dev",
        "contao/manager-bundle": "4.9.*"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

**Comment by coastforge-mei** [comment]
Der Fehler ist mit der 4.0.1 behoben. Danke fürs Melden.

**Comment by arboc** [comment]
Danke
