### ISSUE TITLE
Installtool nicht aufrufbar

### ISSUE THREAD

**Issue by Benjamin-Scherf** [Kuestenschmiede/ForumBundle#3]
Hallo.

Bei der Installation der Extension über den Conatao Manger tritt ein Fehler auf. 

Die Installation läuft einwandfrei durch. Beim Aufruf des Installtools "Es ist ein Fehler aufgetreten". Das Logfile gibt folgenden Fehler aus. 

[2018-02-23 21:32:22] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: preg_match() expects parameter 2 to be string, null given at /www/htdocs/w017e97d/gigatron.online/vendor/contao/core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php:202)"} []

Das con4gis-Core lässt sich installieren.

Contao 4.5.4
Contao-Manager Beta16

**Comment by coastforge-mei** [comment]
Danke für die Info. Wir konzentrieren uns zurzeit auf die LTS und haben noch keine 4.5er Tests gemacht. Wir werden das schnellstmöglich nachholen und korrigieren.

**Comment by coastforge-mei** [comment]
Moin,
hab' gerade mal einen Test gemacht. Bei mir war die Installation in der 4.5.6 problemlos möglich. Wir haben aber in den letzten Tagen auch noch ein paar Änderungen gemacht. Ggf. war der Fehler bereits behoben. Bitte prüfen.

**Comment by seibtph** [comment]
Also in der 4.6.6 habe ich derzeit den gleichen Fehler. Das Bundle wurde installiert, aber das Install-Tool ist nicht aufrufbar. Habt ihr es schon für die 4.6 getestet?

**Comment by coastforge-mei** [comment]
Ja, wir nutzen in mehreren Installationen die 4.6. Das Installtool läuft problemlos. Wir werden das in den nächsten Tagen noch mal genauer unter die Lupe nehmen.

**Comment by coastforge-cro** [comment]
Der Fehler ist in der Forum-Version 3.2.5 gefixt und das Installtool lässt sich wieder aufrufen.
