### ISSUE TITLE
Installation unter Contao 4.13, PHP 8

### ISSUE THREAD

**Issue by rustykowski** [Kuestenschmiede/ForumBundle#32]
Ich bin Erstanwender und installiere das Forum zum ersten Mal.
Mit der oben genannten Umgebung erhalte ich das Forum in der Version 4.1.16 sowie als Abhängigkeit den den Con4Gis Core in der Version 6.0.4 (laut composer.lock).
Müsste nicht der Core in Version 8.x geladen werden?

**Comment by rustykowski** [comment]
Im Backend erscheint das Modul Con4Gis 8. Insofern wird wohl alles seine Richtigkeit haben. :-)

**Comment by coastforge-mei** [comment]
Ja, genau. con4gis ist eine lose Sammlung von Bundles für Geoinformationssysteme und andere Webanwendungen. Die Version wird durch den Hauptbaustein "Maps" bestimmt.
