### ISSUE TITLE
Versions Konflikte

### ISSUE THREAD

**Issue by steffenu** [Kuestenschmiede/ForumBundle#33]
Egal wie ich es anstelle ich kriege das Forum Bundle nicht ohne irgendwelche Versions Konflikte installiert. 

composer require con4gis/forum

getestet mit ->
Contao 4.13
Contao 4.12
Contao 4.11

Php 7.4.28

Das zieht sich durch alle Pakete von Con4gis
Muss dann wohl wieder 4.9 nutzen sonst ;( . Wann kommt support für die neueren Versionen ?

**Comment by coastforge-rro** [comment]
Kannst du uns deine composer.json zukommen lassen? Wir können das Problem nicht nachstellen.

**Comment by steffenu** [comment]
Die Fehlermeldung bei 4.11
 - psr/cache 2.0.0 requires php >=8.0.0 -> your php version (7.4.28) does not satisfy that requirement.

Bei 4.12 hatte ich ne menge andere probleme... Dort lag es aber vllt dann an eigenen Bundles ?

{
  "name": "contao/managed-edition",
  "type": "project",
  "description": "Contao Managed Edition",
  "license": "LGPL-3.0-or-later",
  "require": {
    "contao/calendar-bundle": "4.11.1",
    "contao/comments-bundle": "4.11.1",
    "contao/conflicts": "*@dev",
    "contao/faq-bundle": "4.11.1",
    "contao/listing-bundle": "4.11.1",
    "contao/manager-bundle": "4.11.1",
    "contao/news-bundle": "4.11.1",
    "contao/newsletter-bundle": "4.11.1",
    "contao/official-demo": "^4.11",
    "doctrine/annotations": "^1.13",
    "terminal42/contao-easy_themes": "^2.2"
  },
  "conflict": {
    "contao-components/installer": "<1.3"
  },
  "extra": {
    "contao-component-dir": "assets"
  },
  "autoload": {
    "classmap": [
      "src/ContaoManagerPlugin.php"
    ],
    "psr-4": {
      "": "src/"
    }
  },
  "scripts": {
    "post-install-cmd": [
      "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
    ],
    "post-update-cmd": [
      "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
    ]
  },
  "repositories": []
}

**Comment by steffenu** [comment]
Hier die 4.12 composer json... wobei ich hier nun noch ein paar Sachen entfernt habe ( habe nicht getestet ob es jetzt durchläuft)

{
  "type": "project",
  "require": {
    "contao/calendar-bundle": "4.12.*",
    "contao/comments-bundle": "4.12.*",
    "contao/conflicts": "*@dev",
    "contao/faq-bundle": "4.12.*",
    "contao/listing-bundle": "4.12.*",
    "contao/manager-bundle": "4.12.*",
    "contao/news-bundle": "4.12.*",
    "contao/newsletter-bundle": "4.12.*",
    "markocupic/contao-bundle-creator-bundle": "^1.4"
  },
  "autoload": {
    "psr-4": {
      "": "src/"
    }
  },
  "extra": {
    "contao-component-dir": "assets"
  },
  "scripts": {
    "post-install-cmd": [
      "@php vendor/bin/contao-setup"
    ],
    "post-update-cmd": [
      "@php vendor/bin/contao-setup"
    ]
  }

}

**Comment by coastforge-rro** [comment]
Beide Varianten laufen bei mir problemlos durch. Bist du sicher, dass es die richtige composer.json ist? Wie die Fehlermeldung schon sagt, erfordert das Paket psr/cache ab Version 2.0 PHP 8.0 oder größer. Keines der Pakete in der composer.json will aber psr/cache zwingend in der Version 2.0.

**Comment by steffenu** [comment]
> Beide Varianten laufen bei mir problemlos durch. Bist du sicher, dass es die richtige composer.json ist? Wie die Fehlermeldung schon sagt, erfordert das Paket psr/cache ab Version 2.0 PHP 8.0 oder größer. Keines der Pakete in der composer.json will aber psr/cache zwingend in der Version 2.0.

Ich habs jetzt mit 4.9 ohne probleme installieren können ( sogar über contao manager) ... die anderen versionen schmeissen wie gesagt diese fehlermeldungen und die installation schlägt fehl.... auf 2 pcs getestet bei mir mit 4.11 u  4.12 ...  und beim kollegen auf  4.13 ... Ich teste das nochmal übernächste Woche mit einer frischen 4.13 + php 7.4 ..

**Comment by coastforge-rro** [comment]
Ihr müsst herausfinden, welches Paket psr/cache in der Version 2.0 haben möchte und das ersetzen oder eine andere Version verwenden, die sich auch mit 1.0 zufrieden gibt. Ihr könnt auch auf PHP 8 updaten. Auf jeden Fall hat das Problem nichts mit con4gis zu tun.
