### ISSUE TITLE
Download-Link von Uploaddateien nicht geeignet für geschützte Verzeichnisse

### ISSUE THREAD

**Issue by do-while** [Kuestenschmiede/ForumBundle#34]
Hallo,

Ich habe ein geschütztes, nicht öffentliches Upload-Verzeichnis. Wenn ich im Forum in einem Thema einen Dateianhang (Upload) eintrage, dann wird die Datei auch hochgeladen und dort gespeichert. Der Link im Forum funktioniert jedoch nicht, da die Datei nicht direkt erreichbar ist.
Hier müßte der Link so ausgeführt werden, wie bei dem Download- oder Downloads-Inhaltselement aus dem Core.
Dort funktioniert der Upload, weil Contao die Datei per PHP liest und den Inhalt dann als Download aussendet.

Anwendung bei mir ist ein interner Bereich eines Vereins, mit vertraulichen Dokumenten des Vorstands. Die dürfen nicht in öffentlichen Verzeichnissen liegen.

Gruß aus Berlin
Hagen

**Comment by coastforge-mei** [comment]
Hallo Hagen,

sorry, hab Dein Issue jetzt erst gesehen. Wir prüfen das schnellstmöglich.

Beste Grüße
Matthias

**Comment by coastforge-mei** [comment]
Du hast Recht, dass sollten wir auf jeden Fall umbauen. Für den Umbau brauchen wir allerdings Zeit. Ich bringe das in die Planung, kann aber nichts versprechen.

**Comment by do-while** [comment]
Hallo Matthias,
da freue ich mich drauf.

Hast Du einen Tipp für mich, ob ich das Quick&Dirty über ein Template anpassen kann.
Meist muss dann zusätzlich ein leeres Downloads-Element mit auf der Seite sein, dann klappt es, weil dieses Element dann den eigentlichen Download bedient.

**Comment by coastforge-mei** [comment]
Hallo Hagen,

der Kollege hat eine Lösung implementiert. Bitte mal testen.

**Comment by do-while** [comment]
Leider komme ich an die 4.1.12 noch nicht heran, sie wurde nicht in Packagist synchronisiert. In der Installation wird weiterhin die 4.1.11 als neueste Version geführt.

**Comment by coastforge-mei** [comment]
Moin Hagen,

es dauert ja immer etwas, bis die Versionen im Manager auftauchen. Als Du das gepostet hattest, war ich davon ausgegangen, dass alles normal ist. Leider habe ich erst heute gesehen, dass ein Typo in der Versionsnummer drin war v**.**4.1.12 anstelle v4.1.12. Im nachhinein war es aber gut so, denn der Kollege hatte noch einen Fehler gefunden. Die Version 4.1.13 funktioniert jetzt so, dass die Dateien für Mitglieder geschützt werden können.

Beste Grüße
Matthias

**Comment by do-while** [comment]
Jetzt konnte ich auf die neueste Version aktualisieren - vielen Dank.

Leider funktioniert das bei mir immer noch nicht. Ich beschreiben mal meine Vorgebensweise:
1) Ich lege einen Forenbeitrag oder eine Antwort an, dort hefte ich mit dem Büroklammer-Icon eine PDF-Datei an.
2) Die Datei lädt auch hoch in das Verzeichnis **files/dm/upload/docs/2022-07-27/{hash}.pdf**
3) Der Verzeichnisbaum ist aber nicht öffentlich, im Backend erkennbar an dem Schloss
4) Im Forenbeitrag wird für den Download der folgende Link generiert:
**https://mydomian.tld/files/dm/upload/docs/2022-07-27/5c407a70f40f6450cec67fda28542c28.pdf**
als ein Link auf eine nicht zugängliche Datei (Thema des Issue)

Eigentlich sollte der Download-Link wie bei einem Download-Inhaltselement aufgebaut sein mit Get-Parameter 
**?file=files/dm/upload/docs/2022-07-27/5c407a70f40f6450cec67fda28542c28.pdf**
und dem Handling des Download-Elements

**Comment by coastforge-rro** [comment]
Moin,

es gab leider noch einen Fehler, aber jetzt sollte es endlich laufen.

Für den Link haben wir eine andere Lösung gewählt, aber damit solltest du leben können.

**Comment by do-while** [comment]
Vielen Dank, jetzt klappt es!
