### ISSUE TITLE
getMemberGroupsForForum required frontendUser missing

### ISSUE THREAD

**Issue by rabauss** [Kuestenschmiede/ForumBundle#6]
The required Parameter $frontendUser is missing in:https://github.com/Kuestenschmiede/ForumBundle/blob/384932012b97df7609d273f24ccb7fa17e679cbe/Resources/contao/modules/C4GForum.php#L3347

it should be:
```
            $user = FrontendUser::getInstance();
            $groups = $this->helper->getMemberGroupsForForum($forumId,$user->getData()['id']);
```

or the signature of `getMemberGroupsForForum` has to be changed!

**Comment by coastforge-mei** [comment]
fixed in v3.1.8
