### ISSUE TITLE
Spalten in der Übersicht lassen sich nicht ausblenden

### ISSUE THREAD

**Issue by thepixture** [Kuestenschmiede/ForumBundle#7]
Wenn man in den Experten-Einstellungen des Forum-Moduls die Häkchen für das Ausblenden der Felder (Letzter, Letzter am, Verfasser, Erstellt am, #) setzt, wird im Frontend lediglich das Feld "#" ausgeblendet

**Comment by coastforge-rro** [comment]
Danke für die Meldung, wir arbeiten an dem Problem.

**Comment by coastforge-rro** [comment]
Inzwischen können wir das Problem nicht mehr nachstellen. Besteht es weiterhin?

**Comment by thepixture** [comment]
Ja, leider besteht das Problem noch in der Version 3.2.5

**Comment by coastforge-rro** [comment]
In welcher Contao Version?

**Comment by thepixture** [comment]
Contao 4.4.18

**Comment by coastforge-mei** [comment]
Der Fehler tritt in der aktuellen Version 3.6.0 nicht auf. Ich schliesse dieses Issue.
