### ISSUE TITLE
Bewertungsdurchschnitt wird nicht immer im erstem Beitrag angezeigt

### ISSUE THREAD

**Issue by thepixture** [Kuestenschmiede/ForumBundle#8]
Ich hab festgestellt, dass innerhalb eines Themas, im ersten Beitrag nicht immer der Durchschnitt der Bewertungen angezeigt wird. Egal ob nur eine Bewertung oder mehrere abgegeben wurden.

**Comment by coastforge-rro** [comment]
Die Bewertungen werden auf einer "pro Beitrag"-Basis vergeben. Die Bewertung im Beitrag ist also die, die von diesem Beitrag vergeben wurde und nicht der Themendurchschnitt.
