### ISSUE TITLE
Benachrichtigung wird nicht versendet

### ISSUE THREAD

**Issue by Sizoberz** [Kuestenschmiede/ForumBundle#9]
Habe im Notification center eine neue Benachrichtigung für neue Themen angelegt.
Diese im Modul entsprechend aktiviert. Es wird jedoch in einem abonnierten Forum keine Nachricht versendet. Alle anderen Benachrichtungen des Notification center funktionieren einwandfrei.

**Comment by Sizoberz** [comment]
Sorry - habe mit eigenem user getestet - macht sinn das dann keine Benachrichtigung kommt. Von einem anderen user kommt die Benachrichtigung.

**Comment by coastforge-rro** [comment]
Danke für die Info, dann werde ich den Issue schließen.

**Comment by Sizoberz** [comment]
Nein - funktioniert doch nicht wie gewollt

**Comment by Sizoberz** [comment]
Habe als Empfänger ##user_email##, ##admin_email##
Admin bekommt keine Nachricht und doch nur der user selbst bekommt eine Benachrichtigung. Man bekommt aber keine Benachrichtigung wenn jemand anders ein neues Thema anfängt obwohl man das Forum abonniert hat

**Comment by coastforge-rro** [comment]
Wir werden gleich eine neue Version veröffentlichen, die den Fehler behebt.

**Comment by Sizoberz** [comment]
Super Danke!
Gebt ihr bitte bescheid wenn die Version verfügbar ist?

**Comment by coastforge-mei** [comment]
Ist verfügbar.

**Comment by Sizoberz** [comment]
Funktioniert - Vielen Dank!

**Comment by Sizoberz** [comment]
noch eine Frage
##action_pre##
##action_name_with_subject##
##post_content##
##unsubscribe_link##
##unsubscribe_all_link##
liefern bei mir kein Ergebnis - die Platzhalter werden so als Text wiedergegeben.

**Comment by coastforge-rro** [comment]
Wir werden uns das nochmal anschauen.
